import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
  style={{
    margin: 0,
    fontFamily: "system-ui, -apple-system, sans-serif",
    backgroundColor: "#f8f8f8",
    color: "#111",
  }}
>
  <div
    style={{
      maxWidth: 960,
      margin: "0 auto",
      padding: "40px 24px",
    }}
  >
   <header
  style={{
    borderBottom: "1px solid #eee",
    paddingBottom: 16,
    marginBottom: 28,
  }}
>
  <nav style={{ display: "flex", gap: 14, alignItems: "baseline", flexWrap: "wrap" }}>
    <a href="/" style={{ textDecoration: "none", color: "inherit", fontWeight: 800 }}>
      Merch Archive
    </a>

    <a href="/artists" style={{ textDecoration: "none", color: "inherit" }}>
      Artists
    </a>

    <a href="/search" style={{ textDecoration: "none", color: "inherit" }}>
      Search
    </a>

    <a href="/collection" style={{ textDecoration: "none", color: "inherit" }}>
      My Collection
    </a>

    <a href="/wantlist" style={{ textDecoration: "none", color: "inherit" }}>
      Wantlist
    </a>

    <a href="/add-artist" style={{ textDecoration: "none", color: "inherit" }}>
      Add Artist
    </a>

    <a href="/add-design" style={{ textDecoration: "none", color: "inherit" }}>
      Add Design
    </a>

    <a href="/add-variant" style={{ textDecoration: "none", color: "inherit" }}>
      Add Variant
    </a>

    <span style={{ marginLeft: "auto" }}>
      <a href="/login" style={{ textDecoration: "none", color: "inherit" }}>
        Login
      </a>
    </span>
  </nav>
</header>
    {children}
  </div>
</body>
    </html>
  );
}
